#!/bin/sh
# Regenerate — and publish — the Homebrew formula + Scoop manifest for a dove
# release.
#
#   scripts/render-tap-files.sh [--dry-run] <version> [homebrew-tap-dir] [scoop-bucket-dir]
#
# Fetches the release's SHA256SUMS and writes both tap files with the right
# version, URLs, and checksums — no checksum is ever pasted by hand — then
# commits and pushes each through the git-ark vault (which mirrors to GitHub).
# --dry-run writes the files and prints the push commands without pushing. Tap
# dirs default to the sibling repos ../homebrew-tap and ../scoop-bucket.
#
# See docs/RELEASING.md.
set -eu

DRY=0
args=""
for a in "$@"; do
  case "$a" in
    --dry-run) DRY=1 ;;
    *) args="$args $a" ;;
  esac
done
# shellcheck disable=SC2086
set -- $args

VERSION="${1:?usage: render-tap-files.sh [--dry-run] <version> [brew-dir] [scoop-dir]}"
case "$VERSION" in v*) ;; *) VERSION="v$VERSION" ;; esac
VER="${VERSION#v}" # bare version, e.g. 0.1.0

here=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd) # dove repo root
BREW_DIR="${2:-$here/../homebrew-tap}"
SCOOP_DIR="${3:-$here/../scoop-bucket}"
REPO="boomctl/dove"
BASE="https://github.com/$REPO/releases/download/$VERSION"
MSG="dove $VER"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT INT TERM

echo "fetching SHA256SUMS for $VERSION"
curl -fsSL --proto '=https' "$BASE/SHA256SUMS" -o "$tmp/SHA256SUMS" ||
  { echo "no SHA256SUMS for $VERSION — is the release published?" >&2; exit 1; }

sha() { # asset-name -> its hash (fails loudly if the asset is missing)
  h=$(grep " $1\$" "$tmp/SHA256SUMS" | awk '{print $1}')
  [ -n "$h" ] || { echo "no checksum for $1 in SHA256SUMS" >&2; exit 1; }
  printf '%s' "$h"
}

SHA_ARM_MAC=$(sha dove-aarch64-apple-darwin)
SHA_X64_MAC=$(sha dove-x86_64-apple-darwin)
SHA_ARM_LINUX=$(sha dove-aarch64-unknown-linux-musl)
SHA_X64_LINUX=$(sha dove-x86_64-unknown-linux-musl)
SHA_WIN=$(sha dove-x86_64-pc-windows-msvc.exe)

mkdir -p "$BREW_DIR/Formula"
cat >"$BREW_DIR/Formula/dove.rb" <<EOF
# dove Homebrew formula — GENERATED by dove's scripts/render-tap-files.sh.
# Do not hand-edit; regenerate for a new release rather than patching checksums.
#
#   brew install boomctl/tap/dove
class Dove < Formula
  desc "Send a file out of your own cloud — encrypted, expiring, one command"
  homepage "https://dove.sh"
  version "$VER"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$BASE/dove-aarch64-apple-darwin"
      sha256 "$SHA_ARM_MAC"
    end
    on_intel do
      url "$BASE/dove-x86_64-apple-darwin"
      sha256 "$SHA_X64_MAC"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/dove-aarch64-unknown-linux-musl"
      sha256 "$SHA_ARM_LINUX"
    end
    on_intel do
      url "$BASE/dove-x86_64-unknown-linux-musl"
      sha256 "$SHA_X64_LINUX"
    end
  end

  def install
    bin.install Dir["dove-*"].first => "dove"
  end

  test do
    assert_match "dove #{version}", shell_output("#{bin}/dove --version")
  end
end
EOF

mkdir -p "$SCOOP_DIR/bucket"
cat >"$SCOOP_DIR/bucket/dove.json" <<EOF
{
    "version": "$VER",
    "description": "Send a file out of your own cloud — encrypted, expiring, one command.",
    "homepage": "https://dove.sh",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "$BASE/dove-x86_64-pc-windows-msvc.exe#/dove.exe",
            "hash": "$SHA_WIN"
        }
    },
    "bin": "dove.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/boomctl/dove/releases/download/v\$version/dove-x86_64-pc-windows-msvc.exe#/dove.exe"
            }
        },
        "hash": {
            "url": "https://github.com/boomctl/dove/releases/download/v\$version/SHA256SUMS"
        }
    }
}
EOF

echo "wrote:"
echo "  $BREW_DIR/Formula/dove.rb"
echo "  $SCOOP_DIR/bucket/dove.json"
echo

if [ "$DRY" -eq 1 ]; then
  echo "dry-run — publish through git-ark with:"
  echo "  (cd \"$BREW_DIR\"  && git commit -am \"$MSG\" && git push git-ark:homebrew-tap main)"
  echo "  (cd \"$SCOOP_DIR\" && git commit -am \"$MSG\" && git push git-ark:scoop-bucket main)"
  exit 0
fi

# Commit + push each tap file through the git-ark vault (which mirrors to GitHub).
publish() { # <dir> <file-within-repo> <vault-remote>
  ( cd "$1"
    git add "$2"
    if git diff --cached --quiet; then
      echo "  $3: already at $MSG"
    else
      git commit -q -m "$MSG"
      git push "$3" main
      echo "  $3: published $MSG"
    fi )
}

echo "publishing through git-ark:"
publish "$BREW_DIR"  "Formula/dove.rb"  git-ark:homebrew-tap
publish "$SCOOP_DIR" "bucket/dove.json" git-ark:scoop-bucket
