#!/usr/bin/env bash
#
# Render the Homebrew formula and Scoop manifest for a dove release, filling in
# the version and the per-artifact SHA-256s from the release's SHA256SUMS file.
# The release workflow calls this after publishing; you can also run it locally
# against a downloaded SHA256SUMS to preview or hand-publish a manifest.
#
#   packaging/render.sh <version> <SHA256SUMS path> <out dir>
#
# It writes <out>/homebrew/dove.rb and <out>/scoop/dove.json — the layout of the
# sibling boomctl formulae (bare binaries, on_arm/on_intel, .exe#/rename).
set -euo pipefail

version="${1:?usage: render.sh <version> <SHA256SUMS> <out-dir>}"
sums="${2:?usage: render.sh <version> <SHA256SUMS> <out-dir>}"
out="${3:?usage: render.sh <version> <SHA256SUMS> <out-dir>}"

repo="boomctl/dove"
base="https://github.com/${repo}/releases/download/v${version}"

# The checksum for one artifact, by exact filename, from a `sha256sum` manifest
# (`<hash>␠␠<name>` per line). Fails loudly if the artifact is missing.
sha() {
  local name="$1" line
  line=$(grep -E "  ${name}\$" "$sums") || {
    echo "render.sh: no checksum for '${name}' in ${sums}" >&2
    exit 1
  }
  printf '%s' "${line%% *}"
}

d_arm=$(sha "dove-aarch64-apple-darwin")
d_x64=$(sha "dove-x86_64-apple-darwin")
l_arm=$(sha "dove-aarch64-unknown-linux-musl")
l_x64=$(sha "dove-x86_64-unknown-linux-musl")
w_x64=$(sha "dove-x86_64-pc-windows-msvc.exe")

mkdir -p "${out}/homebrew" "${out}/scoop"

# ── Homebrew formula ─────────────────────────────────────────────────────────
# Binary formula: download the prebuilt binary for the running platform and
# install it as `dove`. macOS (arm/intel) + Linux (arm/intel via musl).
cat > "${out}/homebrew/dove.rb" <<RB
# dove Homebrew formula — GENERATED by dove's packaging/render.sh.
# Do not hand-edit; regenerate for a new release rather than patching checksums.
#
#   brew install boomctl/tap/dove
class Dove < Formula
  desc "Send a file out of your own cloud — encrypted, expiring, one command"
  homepage "https://dove.sh"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/dove-aarch64-apple-darwin"
      sha256 "${d_arm}"
    end
    on_intel do
      url "${base}/dove-x86_64-apple-darwin"
      sha256 "${d_x64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/dove-aarch64-unknown-linux-musl"
      sha256 "${l_arm}"
    end
    on_intel do
      url "${base}/dove-x86_64-unknown-linux-musl"
      sha256 "${l_x64}"
    end
  end

  def install
    bin.install Dir["dove-*"].first => "dove"
  end

  test do
    assert_match "dove #{version}", shell_output("#{bin}/dove --version")
  end
end
RB

# ── Scoop manifest ───────────────────────────────────────────────────────────
# Windows x64. The #/dove.exe fragment tells Scoop to save the bare download as
# dove.exe. \$version in autoupdate is a Scoop template var (kept literal), so its
# excavator can also bump the manifest between our pushes.
cat > "${out}/scoop/dove.json" <<JSON
{
    "version": "${version}",
    "description": "Send a file out of your own cloud — encrypted, expiring, one command.",
    "homepage": "https://dove.sh",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "${base}/dove-x86_64-pc-windows-msvc.exe#/dove.exe",
            "hash": "${w_x64}"
        }
    },
    "bin": "dove.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/${repo}/releases/download/v\$version/dove-x86_64-pc-windows-msvc.exe#/dove.exe"
            }
        },
        "hash": {
            "url": "https://github.com/${repo}/releases/download/v\$version/SHA256SUMS"
        }
    }
}
JSON

echo "render.sh: wrote ${out}/homebrew/dove.rb + ${out}/scoop/dove.json for v${version}"
